[package]
name = "density_clustering_bin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
density_clustering = { path = "../density_clustering" }
num-traits = "0.2.18"
serde = "1.0.197"
serde_json = "1.0.114"
