name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up uv package manager
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: npm install

      - uses: actions/cache@v4
        id: cache-demo-data
        with:
          path: packages/docs/demo-data
          key: ${{ runner.os }}-${{ hashFiles('packages/docs/generate_demo_data.py') }}

      - name: Generate demo data
        if: steps.cache-demo-data.outputs.cache-hit != 'true'
        run: cd packages/docs && uv run generate_demo_data.py

      - name: Run custom build script
        run: ./scripts/build.sh
